### ISSUE TITLE
Google Captcha

### ISSUE THREAD

**Issue by sweetcharity** [killswitch-GUI/SimplyEmail#10]
Where should I resolve google capcha?

**Comment by killswitch-GUI** [comment]
Please explain in more depth the issues your experiencing. Is the issue you are getting alerted that SimplyEmail is warning of Google Captcha, and would want to know how to resolve? Something to keep in mind if you're over a public VPN, you have a large chance of getting rapidly blocked by google. Also, if you're running multiple searches and encounter Google Captcha simply open Google and fill out the captcha and re-run. I hope to implement a random User-Agent pool soon.

**Comment by sweetcharity** [comment]
>> Is the issue you are getting alerted that SimplyEmail is warning of Google Captcha, and would want to know how to resolve? 

yes

>> simply open Google and fill out the captcha and re-run

Doesn't help. I'm using TOR - there is a problem I think

**Comment by killswitch-GUI** [comment]
Yea, TOR pounds you with Captcha! I will be trying to implement a Captcha forward soon. Random User Agents were just added as well. Let me know if there is anything i can help or improve on! :+1:

**Comment by ChrisTruncer** [comment]
Can you please release a bypass for the captcha?

**Comment by killswitch-GUI** [comment]
Hmm let me go dec something
