### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by arch3angel** [killswitch-GUI/SimplyEmail#14]
I recently updated the code and after execution I got the following error:
# 

Traceback (most recent call last):
  File "./SimplyEmail.py", line 106, in <module>
    main()
  File "./SimplyEmail.py", line 99, in main
    orc.title()
  File "/opt/simplyemail/Common/TaskController.py", line 745, in title
    print " Current Version: " + self.version + " | Website: CyberSyndicates.com"

I re-ran the setup and received no errors, yet it still fails to execute.

I also attempted to delete the directory, and re-clone the repo, still no resolve.

Thoughts?

**Comment by arch3angel** [comment]
I installed and ran the tool on a fresh Ubuntu box verse my Kali box and it appears to run properly.

Not sure why the update on the Kali box broke the tool, but I hope this test helps.

**Comment by killswitch-GUI** [comment]
@arch3angel will take a look, kali has been a issue lately with configparser. About to just install it in the helpers lol.

**Comment by jteslaxxx** [comment]
Have same issue, using BackBox Ubuntu i386!

**Comment by killswitch-GUI** [comment]
Just gor back from some time off, will get a fix out for this today.

**Comment by killswitch-GUI** [comment]
Does this work @arch3angel 

`sudo apt-get remove python-configparser`
`sudo apt-get -y install python-configparser`

**Comment by jteslaxxx** [comment]
tried not working, still getting this output:
 ============================================================
Traceback (most recent call last):
  File "SimplyEmail.py", line 106, in <module>
    main()
  File "SimplyEmail.py", line 99, in main
    orc.title()
  File "/opt/SimplyEmail/Common/TaskController.py", line 745, in title
    print " Current Version: " + self.version + " | Website: CyberSyndicates.com"
AttributeError: 'Conducter' object has no attribute 'version'

**Comment by killswitch-GUI** [comment]
grabing a new image to test I cant reproduce.

**Comment by guitarmanj** [comment]
I too am getting the 'AttributeError: 'Conducter' object has no attribute 'version'' error :/

**Comment by juushya** [comment]
@killswitch-GUI Same error on `Ubuntu 14.04 LTS Trusty x86_64`. Any fixes yet..? Thanks.

**Comment by killswitch-GUI** [comment]
Fixed @juushya moving project to virtual env moving forward to prevent different python packages.
