### ISSUE TITLE
Easier automation

### ISSUE THREAD

**Issue by Faelian** [killswitch-GUI/SimplyEmail#15]
I am currently automating SimplyEmail in script, I think there could be a feature to make it easier.
It could take different form such as adding an option to write the results in stdout, or to specify the text file that will be outputed.

For example theHarvester has a -f option to generate an xml file with the gathered emails.

The easier way would probably be to add a way to add a -o to choose where to write the results.
I can write the code if you are interested.

**Comment by killswitch-GUI** [comment]
You bring up a great point! At this point using stdout would probably be a bad idea. I can’t account for changes in python or libraries. So if one of those fails or prints verbose you could have mixed data. I’m thinking for this I implement a JSON output do to its ease and easy object assignment. Simply specify the -json "json.txt" and parse that with ease. 

Also is name generation needed? 

I will make this option avoid all return stats as well as user interaction.

**Comment by killswitch-GUI** [comment]
@Faelian Fa Right now i have the "dev-json" branch working only on the "-t" test module feature. It currently only works on the basic email enumeration. I will be adding in the verify email function and name creation soon. Would output like this work? I feel like this would be the best route with the simplicity of JSON.
```
{
    "domain_of_collection": "test.com", 
    "email_collection_count": 8, 
    "current_version": "v1.4", 
    "data_of_collection": "29/05/2016", 
    "time_of_collection": "10:56:19", 
    "emails": [
        {
            "module_name": "Yahoo Search for Emails", 
            "collection_data": "29/05/2016", 
            "email": "recruiting@test.com", 
            "collection_time": "10:56:17"
        }, 
        {
            "module_name": "Yahoo Search for Emails", 
            "collection_data": "29/05/2016", 
            "email": "recruiting@test.com", 
            "collection_time": "10:56:17"
        }, 
        {
            "module_name": "Yahoo Search for Emails", 
            "collection_data": "29/05/2016", 
            "email": "recruiting@test.com", 
            "collection_time": "10:56:17"
        }, 
        {
            "module_name": "Yahoo Search for Emails", 
            "collection_data": "29/05/2016", 
            "email": "recruiting@test.com", 
            "collection_time": "10:56:17"
        }, 
        {
            "module_name": "Yahoo Search for Emails", 
            "collection_data": "29/05/2016", 
            "email": "recruiting@test.com", 
            "collection_time": "10:56:17"
        }, 
        {
            "module_name": "Yahoo Search for Emails", 
            "collection_data": "29/05/2016", 
            "email": "recruiting@test.com", 
            "collection_time": "10:56:17"
        }, 
        {
            "module_name": "Yahoo Search for Emails", 
            "collection_data": "29/05/2016", 
            "email": "recruiting@test.com", 
            "collection_time": "10:56:17"
        }, 
        {
            "module_name": "Yahoo Search for Emails", 
            "collection_data": "29/05/2016", 
            "email": "recruiting@test.com", 
            "collection_time": "10:56:17"
        }
    ], 
    "tool_of_collection": "SimplyEmail"
}
```

**Comment by Faelian** [comment]
Wow, thanks for taking a look at it during the Week-End.
I agree, using json is the way to go.
Name generation would indeed be very useful, and an output like this would work. I don't think I will ever use module_name, collection_data and collection_time of the email list.

Also, I don't know if it's possible, but something that would be really useful is listing the source of the information. E.g if the email address has been found on Linkedin, the URL of the Linkedin profile.
Even better if all the sources for one email address are listed. But all this could be for a future version.

**Comment by killswitch-GUI** [comment]
@Faelian --json is in !
