### ISSUE TITLE
Error in File Location: 

### ISSUE THREAD

**Issue by TunisianWhiteHatSecurity** [killswitch-GUI/SimplyEmail#16]
In Common/TaskController, i suggest to change the lines 774 & 775
`        Line += "   File Location: \t\t" + \
            os.getcwd() + str(domain) + "-" + str(self.TimeDate) + "\n"`
by 
`        Line += "   File Location: \t\t" + \
            os.getcwd() + "/" + str(domain) + "-" + str(self.TimeDate) + "\n"`
because it gives a wrong file location 
Ps; i am working with Ubuntu.

**Comment by killswitch-GUI** [comment]
Ahh, I see that issue, I will fix that today. Nice catch!

**Comment by killswitch-GUI** [comment]
fixed

**Comment by TunisianWhiteHatSecurity** [comment]
quickly fixed.
