### ISSUE TITLE
Installation script brakes Kali 

### ISSUE THREAD

**Issue by Indeserpen** [killswitch-GUI/SimplyEmail#24]
Your Setup.sh brakes python libraries in Kali Linux
Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

root@kali:/opt/OSINT/SimplyEmail/setup# ./Setup.sh
# 
#  SimpleEmail Setup Script | [Updated]: 2016
#  [Web]: Http://CyberSyndicates.com | [Twitter]: @KillSwitch-GUI

 [*] Installing and updating requests libary
Already up-to-date.
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following packages were automatically installed and are no longer required:
  augeas-lenses dkms ipxe-qemu libadns1 libaugeas0 libboost-system1.58.0
  libboost-thread1.58.0 libcacard0 libfdt1 libfuzzy2 libgeos-3.5.0
  libgeos-c1v5 libgsoap9 libjs-mochikit libmaxminddb0 libnetcf1 librados2
  librbd1 libsdl1.2debian libspice-server1 libusbredirparser1 libvdeplug2
  libvirt-daemon libvirt0 libvncserver1 libxen-4.6 libxenstore3.0
  libxml2-utils libyajl2 linux-headers-amd64 netcat-openbsd osslsigncode pwgen
  python-adns python-advancedhttpserver python-alembic python-boltons
  python-bottle python-capstone python-cheetah python-dap python-django
  python-django-common python-dpkt python-dumbnet python-easygui python-editor
  python-formencode python-geoip2 python-geojson python-icalendar
  python-ipaddr python-levenshtein python-libvirt python-magic
  python-maxminddb python-mpltoolkits.basemap python-mpltoolkits.basemap-data
  python-openid python-pampy python-paste python-pastedeploy
  python-pastedeploy-tpl python-pastescript python-pluginbase python-pydeep
  python-qrcode python-scgi python-smoke-zephyr python-sqlparse python-tempita
  python-termcolor python-tzlocal qemu-kvm qemu-system-common qemu-system-x86
  qemu-utils seabios virtualbox virtualbox-dkms virtualbox-qt
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  backdoor-factory bdfproxy cuckoo kali-linux-full king-phisher maltego-teeth
  python-configparser python-future python-metaconfig python-pefile
  python-pyotp set
0 upgraded, 0 newly installed, 12 to remove and 0 not upgraded.
After this operation, 175 MB disk space will be freed.
(Reading database ... 358777 files and directories currently installed.)
Removing kali-linux-full (2016.2.12) ...
Removing bdfproxy (0.3.9-0kali1) ...
Removing backdoor-factory (3.4.1-0kali1) ...
Removing cuckoo (1.1.1-0kali1) ...
Removing king-phisher (1.4.0-0kali1) ...
Removing maltego-teeth (1.0-1kali0) ...
Removing python-metaconfig (0.1.4a1-3) ...
Removing python-pyotp (2.1.1-1) ...
Removing set (7.3.12-0kali1) ...
Removing python-pefile (2016.3.28-3) ...
Removing python-future (0.15.2-3) ...
Removing python-configparser (3.3.0r2-2kali1) ...
Processing triggers for mime-support (3.60) ...
Processing triggers for desktop-file-utils (0.23-1) ...
Processing triggers for gnome-menus (3.13.3-8) ...
Processing triggers for hicolor-icon-theme (0.15-1) ...
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following packages were automatically installed and are no longer required:
  augeas-lenses dkms ipxe-qemu libadns1 libaugeas0 libboost-system1.58.0
  libboost-thread1.58.0 libcacard0 libfdt1 libfuzzy2 libgeos-3.5.0
  libgeos-c1v5 libgsoap9 libjs-mochikit libmaxminddb0 libnetcf1 librados2
  librbd1 libsdl1.2debian libspice-server1 libusbredirparser1 libvdeplug2
  libvirt-daemon libvirt0 libvncserver1 libxen-4.6 libxenstore3.0
  libxml2-utils libyajl2 linux-headers-amd64 netcat-openbsd osslsigncode pwgen
  python-adns python-advancedhttpserver python-alembic python-boltons
  python-bottle python-capstone python-cheetah python-dap python-django
  python-django-common python-dpkt python-dumbnet python-easygui python-editor
  python-formencode python-geoip2 python-geojson python-icalendar
  python-ipaddr python-levenshtein python-libvirt python-magic
  python-maxminddb python-mpltoolkits.basemap python-mpltoolkits.basemap-data
  python-openid python-pampy python-paste python-pastedeploy
  python-pastedeploy-tpl python-pastescript python-pluginbase python-pydeep
  python-qrcode python-scgi python-smoke-zephyr python-sqlparse python-tempita
  python-termcolor python-tzlocal qemu-kvm qemu-system-common qemu-system-x86
  qemu-utils seabios virtualbox virtualbox-dkms virtualbox-qt
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  python-configparser
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 85.8 kB of archives.
After this operation, 410 kB of additional disk space will be used.
Get:1 http://mirrors.netix.net/kali kali-rolling/main amd64 python-configparser all 3.3.0r2-2kali1 [85.8 kB]
Fetched 85.8 kB in 1s (81.8 kB/s)  
Selecting previously unselected package python-configparser.
(Reading database ... 356428 files and directories currently installed.)
Preparing to unpack .../python-configparser_3.3.0r2-2kali1_all.deb ...
Unpacking python-configparser (3.3.0r2-2kali1) ...
Setting up python-configparser (3.3.0r2-2kali1) ...
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following packages were automatically installed and are no longer required:
  augeas-lenses dkms ipxe-qemu libadns1 libaugeas0 libboost-system1.58.0
  libboost-thread1.58.0 libcacard0 libfdt1 libfuzzy2 libgeos-3.5.0
  libgeos-c1v5 libgsoap9 libjs-mochikit libmaxminddb0 libnetcf1 librados2
  librbd1 libsdl1.2debian libspice-server1 libusbredirparser1 libvdeplug2
  libvirt-daemon libvirt0 libvncserver1 libxen-4.6 libxenstore3.0
  libxml2-utils libyajl2 linux-headers-amd64 netcat-openbsd osslsigncode pwgen
  python-adns python-advancedhttpserver python-alembic python-boltons
  python-bottle python-capstone python-cheetah python-dap python-django
  python-django-common python-dpkt python-dumbnet python-easygui python-editor
  python-formencode python-geoip2 python-geojson python-icalendar
  python-ipaddr python-levenshtein python-libvirt python-maxminddb
  python-mpltoolkits.basemap python-mpltoolkits.basemap-data python-openid
  python-pampy python-paste python-pastedeploy python-pastedeploy-tpl
  python-pastescript python-pluginbase python-pydeep python-qrcode python-scgi
  python-smoke-zephyr python-sqlparse python-tempita python-termcolor
  python-tzlocal qemu-kvm qemu-system-common qemu-system-x86 qemu-utils
  seabios virtualbox virtualbox-dkms virtualbox-qt
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  python-magic
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 73.7 kB disk space will be freed.
(Reading database ... 356480 files and directories currently installed.)
Removing python-magic (1:5.28-4) ...
Reading package lists... Done
Building dependency tree  
Reading state information... Done
python-lxml is already the newest version (3.6.4-1).
python-lxml set to manually installed.
The following packages were automatically installed and are no longer required:
  augeas-lenses dkms ipxe-qemu libadns1 libaugeas0 libboost-system1.58.0
  libboost-thread1.58.0 libcacard0 libfdt1 libfuzzy2 libgeos-3.5.0
  libgeos-c1v5 libgsoap9 libjs-mochikit libmaxminddb0 libnetcf1 librados2
  librbd1 libsdl1.2debian libspice-server1 libusbredirparser1 libvdeplug2
  libvirt-daemon libvirt0 libvncserver1 libxen-4.6 libxenstore3.0
  libxml2-utils libyajl2 linux-headers-amd64 netcat-openbsd osslsigncode pwgen
  python-adns python-advancedhttpserver python-alembic python-boltons
  python-bottle python-capstone python-cheetah python-dap python-django
  python-django-common python-dpkt python-dumbnet python-easygui python-editor
  python-formencode python-geoip2 python-geojson python-icalendar
  python-ipaddr python-levenshtein python-libvirt python-maxminddb
  python-mpltoolkits.basemap python-mpltoolkits.basemap-data python-openid
  python-pampy python-paste python-pastedeploy python-pastedeploy-tpl
  python-pastescript python-pluginbase python-pydeep python-qrcode python-scgi
  python-smoke-zephyr python-sqlparse python-tempita python-termcolor
  python-tzlocal qemu-kvm qemu-system-common qemu-system-x86 qemu-utils
  seabios virtualbox virtualbox-dkms virtualbox-qt
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree  
Reading state information... Done
grep is already the newest version (2.25-6).
libxml2-dev is already the newest version (2.9.4+dfsg1-1+b1).
libxslt1-dev is already the newest version (1.1.29-1).
python-dev is already the newest version (2.7.11-2).
wget is already the newest version (1.18-2+b1).
The following packages were automatically installed and are no longer required:
  augeas-lenses dkms ipxe-qemu libadns1 libaugeas0 libboost-system1.58.0
  libboost-thread1.58.0 libcacard0 libfdt1 libfuzzy2 libgeos-3.5.0
  libgeos-c1v5 libgsoap9 libjs-mochikit libmaxminddb0 libnetcf1 librados2
  librbd1 libsdl1.2debian libspice-server1 libusbredirparser1 libvdeplug2
  libvirt-daemon libvirt0 libvncserver1 libxen-4.6 libxenstore3.0
  libxml2-utils libyajl2 linux-headers-amd64 netcat-openbsd osslsigncode pwgen
  python-adns python-advancedhttpserver python-alembic python-boltons
  python-bottle python-capstone python-cheetah python-dap python-django
  python-django-common python-dpkt python-dumbnet python-easygui python-editor
  python-formencode python-geoip2 python-geojson python-icalendar
  python-ipaddr python-levenshtein python-libvirt python-maxminddb
  python-mpltoolkits.basemap python-mpltoolkits.basemap-data python-openid
  python-pampy python-paste python-pastedeploy python-pastedeploy-tpl
  python-pastescript python-pluginbase python-pydeep python-qrcode python-scgi
  python-smoke-zephyr python-sqlparse python-tempita python-termcolor
  python-tzlocal qemu-kvm qemu-system-common qemu-system-x86 qemu-utils
  seabios virtualbox virtualbox-dkms virtualbox-qt
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  antiword odt2txt
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 145 kB of archives.
After this operation, 683 kB of additional disk space will be used.
Get:1 http://mirrors.netix.net/kali kali-rolling/main amd64 antiword amd64 0.37-11 [132 kB]
Get:2 http://mirrors.netix.net/kali kali-rolling/main amd64 odt2txt amd64 0.5-1+b1 [13.3 kB]
Fetched 145 kB in 1s (111 kB/s)
Selecting previously unselected package antiword.
(Reading database ... 356469 files and directories currently installed.)
Preparing to unpack .../0-antiword_0.37-11_amd64.deb ...
Unpacking antiword (0.37-11) ...
Selecting previously unselected package odt2txt.
Preparing to unpack .../1-odt2txt_0.5-1+b1_amd64.deb ...
Unpacking odt2txt (0.5-1+b1) ...
Processing triggers for mime-support (3.60) ...
Setting up odt2txt (0.5-1+b1) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for hicolor-icon-theme (0.15-1) ...
Setting up antiword (0.37-11) ...
Collecting xlsxwriter
  Downloading XlsxWriter-0.9.3-py2.py3-none-any.whl (136kB)
    100% |████████████████████████████████| 143kB 529kB/s 
Installing collected packages: xlsxwriter
  Found existing installation: XlsxWriter 0.7.3
    Not uninstalling xlsxwriter at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed xlsxwriter-0.9.3
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /usr/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): python-magic in /usr/local/lib/python2.7/dist-packages
Collecting fake-useragent
  Downloading fake-useragent-0.1.2.tar.gz
Building wheels for collected packages: fake-useragent
  Running setup.py bdist_wheel for fake-useragent ... done
  Stored in directory: /root/.cache/pip/wheels/be/63/15/f6e26846756da814630681d9fd98d53310426a8464289d7455
Successfully built fake-useragent
Installing collected packages: fake-useragent
Successfully installed fake-useragent-0.1.2
Requirement already up-to-date: mechanize in /usr/lib/python2.7/dist-packages
Collecting docx2txt
  Downloading docx2txt-0.6.tar.gz
Building wheels for collected packages: docx2txt
  Running setup.py bdist_wheel for docx2txt ... done
  Stored in directory: /root/.cache/pip/wheels/3b/ab/d3/03be281c00dc3bf81cd0f899b4679ee3714b36e15c4125e1bd
Successfully built docx2txt
Installing collected packages: docx2txt
Successfully installed docx2txt-0.6
Requirement already up-to-date: requests in /usr/local/lib/python2.7/dist-packages
Collecting xlsx2csv
  Downloading xlsx2csv-0.7.2.tar.gz (188kB)
    100% |████████████████████████████████| 194kB 477kB/s 
Building wheels for collected packages: xlsx2csv
  Running setup.py bdist_wheel for xlsx2csv ... done
  Stored in directory: /root/.cache/pip/wheels/50/9b/4c/580a8d090c46e32e3fc7644ff211214583d4756ccd6a95c3ef
Successfully built xlsx2csv
Installing collected packages: xlsx2csv
Successfully installed xlsx2csv-0.7.2
Collecting configparser
  Downloading configparser-3.5.0.tar.gz
Building wheels for collected packages: configparser
  Running setup.py bdist_wheel for configparser ... done
  Stored in directory: /root/.cache/pip/wheels/1c/bd/b4/277af3f6c40645661b4cd1c21df26aca0f2e1e9714a1d4cda8
Successfully built configparser
Installing collected packages: configparser
  Found existing installation: configparser 3.3.0.post2
    Not uninstalling configparser at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed configparser-3.5.0
Requirement already up-to-date: BeautifulSoup in /usr/lib/python2.7/dist-packages
Requirement already up-to-date: pdfminer in /usr/lib/python2.7/dist-packages
Requirement already up-to-date: dnspython in /usr/lib/python2.7/dist-packages
root@kali:/opt/OSINT/SimplyEmail/setup#

**Comment by jteslaxxx** [comment]
Plus it fails to start after installation:
Traceback (most recent call last):
  File "./SimplyEmail.py", line 15, in <module>
    from Common import TaskController
  File "/opt/OSINT/SimplyEmail/Common/TaskController.py", line 18, in <module>
    from Helpers import VerifyEmails
  File "/opt/OSINT/SimplyEmail/Helpers/VerifyEmails.py", line 4, in <module>
    import dns.resolver
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 35, in <module>
    import dns.message
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 191
    print('id %d' % self.id, file=s)
                                 ^
SyntaxError: invalid syntax

**Comment by killswitch-GUI** [comment]
Could you pull and re try on that same system?

**Comment by killswitch-GUI** [comment]
Fixed in new release: going to virtual env moving forward since Kali is always changing these days
