### ISSUE TITLE
AttributeError: 'module' object has no attribute '_base'

### ISSUE THREAD

**Issue by bcoles** [killswitch-GUI/SimplyEmail#29]
I received `AttributeError: 'module' object has no attribute '_base'` error when launching SimplyEmail.py on Kali 4.9.0-kali-amd64.

Fixed the issue with `pip install --upgrade beautifulsoup4`

**Comment by killswitch-GUI** [comment]
Thanks for this report. https://github.com/killswitch-GUI/SimplyEmail/blob/master/setup/Setup.sh#L57 missed the flag.
