### ISSUE TITLE
Magic not working on KALI latest

### ISSUE THREAD

**Issue by its0x08** [killswitch-GUI/SimplyEmail#35]
## SimplyEmail Version
Latest

## OS Information (Linux flavor, Python version)
`Linux kali 4.9.0-kali4-amd64 #1 SMP Debian 4.9.30-1kali1 (2017-06-06) x86_64 GNU/Linux`

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
tried many things but couldn't make it work!!!

## Screenshot of error, embedded text output, or Pastebin link to the error
`root@kali:~/Desktop/scripts/SimplyEmail# python2.7 SimplyEmail.py 
Traceback (most recent call last):
  File "SimplyEmail.py", line 13, in <module>
    from Helpers import helpers
  File "/root/Desktop/scripts/SimplyEmail/Helpers/helpers.py", line 7, in <module>
    import magic
ImportError: No module named magic
`

## Any additional information

**Comment by killswitch-GUI** [comment]
@its0x08 did a `sudo pip install python-magic` not do the trick?

**Comment by killswitch-GUI** [comment]
@its0x08 fixed to move to virtualenv
