### ISSUE TITLE
Please use the API

### ISSUE THREAD

**Issue by ColinKeigher** [killswitch-GUI/SimplyEmail#9]
I noticed that you're parsing the Canario (formerly Canary.PW) website instead of using the API. Could you please migrate this code to use that?

**Comment by killswitch-GUI** [comment]
Didn't see their was a change in the site structure. Thanks for this input, I will look into it tonight!

**Comment by killswitch-GUI** [comment]
So just at a glance i noticed that the API must me registered (major limiting factor). So what I'm thinking is I rebuild and update the raw HTML search to be accurate on the new site. Then I add a separate module for the API, it will be the first API module so it will be a nice addition. 

What are your thoughts?

**Comment by ColinKeigher** [comment]
I would prefer that you wouldn't because you're going to run into a problem in about six months. I'll be introducing rate-limiting to prevent abuse to the web interface (you're not the problem just an FYI but I do want to ensure that you're not getting caught up in this) which in turn will require users to accept an agreement before proceeding.

As it stands right now, the registration process is pretty straightforward (just sign up and then confirm via e-mail) and then the API key is generated immediately upon the first login. There will be rate-limiting on that at the same time but the errors will be straightforward to work with.

I can promise you that going with the API will not lead to any substantial future changes (there will be a new API version eventually but the old interface will be maintained), but the web interface is going to under go some changes and it will for sure break what you've got going already and what you're considering as a fix.

Like you can continue as is but I'd prefer that you didn't just so don't have to make too many changes.

May I ask why registration is a major limiting factor?

**Comment by killswitch-GUI** [comment]
ok after digging deeper your 100% correct as I would have imagine if your on the team developing Canario! The site structure has completely changed, and how searches are conducted would need a full rewrite. 

As for the rate-limiting, thanks for that heads up! Which is totally understandable, and is always eventually needed. As for the API, I think your right about moving the module completely over to API based search. If the changes will be consistent, than it would be silly to continue down that route.

As for the registration (limiting factor) issues, its not *major* its just one more step a user has to take to get up and running throughly. It really isn't that major in the long run now I sat back and thought about it. Im just trying to make the tool simple but extremely effective in its searches with out major configuration. I think its time to introduce API based searches, so I'm going to move forward with removing the old module and replacing with a full API based search. 

Also to you and the guys that maintain Canario its epic, and great work! its one of a kind and is extremely effective. Thanks!

**Comment by ColinKeigher** [comment]
Not a problem! I appreciate this very much. Let me know if you have any requests for improvement, features, et cetera. :)

**Comment by killswitch-GUI** [comment]
Am I using the API correctly? I followed the API documentation and not getting proper results. 
https://canar.io/_api/?key=SNIP&action=search&query=hacked

any info or is the API down? 
```
{
  "action": "search", 
  "action_valid": true, 
  "api_key": "snip", 
  "arguments": {
    "action": "search", 
    "key": "snip", 
    "query": "hacked"
  }, 
  "data": {
    "results": {
      "count": 0, 
      "results": [], 
      "timestamp": 1455905973.784281
    }
  }, 
  "error_state": false, 
  "ip_sender": "65.8.148.104", 
  "postdata": null, 
  "query_time": 0.008593082427978516, 
  "server_time": 1455905973.784292
```

**Comment by killswitch-GUI** [comment]
Hey its integrated! Let me know what you think.
